# Generated by Django 5.0.3 on 2024-03-04 21:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('created_datetime', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
